version: '3'

tasks:
  default:
    desc: "Build all binaries"
    cmds:
      - task: build

  build:
    desc: "Build binaries for all platforms (macOS ARM & Linux x86_64)"
    cmds:
      - task: build:mac
      - task: build:linux

  build:mac:
    desc: "Build the go-reauth-proxy binary for macOS (ARM64)"
    env:
      GOOS: darwin
      GOARCH: arm64
    cmds:
      - mkdir -p build
      - go build -ldflags="-s -w" -trimpath -o build/go-reauth-proxy-darwin-arm64 cmd/server/main.go
      - echo "Built macOS ARM64 binary at build/go-reauth-proxy-darwin-arm64"

  build:linux:
    desc: "Build the go-reauth-proxy binary for Linux (AMD64)"
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - mkdir -p build
      - go build -ldflags="-s -w" -trimpath -o build/go-reauth-proxy-linux-amd64 cmd/server/main.go
      - upx --best --lzma build/go-reauth-proxy-linux-amd64 || echo "UPX compression skipped"
      - echo "Built Linux AMD64 binary at build/go-reauth-proxy-linux-amd64"

  run:
    desc: "Run the go-reauth-proxy server (usage: task run -- -proxy-port 8090 -admin-port 8091)"
    cmds:
      - go run cmd/server/main.go {{.CLI_ARGS}}

  run:auth-server:
    desc: "Run the auth-server server (usage: task run:auth-server -- -port 7997)"
    cmds:
      - cd example/auth-server && bun run index.ts --watch {{.CLI_ARGS}}

  test:
    desc: "Run all tests"
    cmds:
      - go test -v ./...

  clean:
    desc: "Clean build artifacts"
    cmds:
      - rm -rf build/
  
  stop:
    desc: "Stop the go-reauth-proxy server"
    cmds:
      - sh -c 'PID=$(lsof -ti:7999); if [ -n "$PID" ]; then kill -9 $PID; echo "Server stopped."; else echo "Server is not running."; fi'
  docs:
    desc: "Generate swagger docs"
    cmds:
      - sh -c 'swag init -d ./cmd/server,./pkg -g main.go -o ./cmd/server/docs && echo "Swagger docs generated at cmd/server/docs"'
  build:auth-server:
    desc: "Build the auth-server binary for Linux (AMD64)"
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - mkdir -p build
      - sh -c 'cd example/auth-server && bun build ./index.ts --compile --target bun-linux-x64 --outfile ../../build/auth-server'
      - echo "Built Linux AMD64 binary at build/auth-server"
    
