// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/license/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth": {
            "get": {
                "description": "Get the configured global authentication URLs and port",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get global auth config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.AuthConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Set the global authentication configurations (port, auth_url, login_url)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set global auth config",
                "parameters": [
                    {
                        "description": "Auth configuration",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AuthConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/config/default-route": {
            "get": {
                "description": "Get the configured default route when root route is requested",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get default route",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Set the configured default route when root route is requested",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set default route",
                "parameters": [
                    {
                        "description": "Route configuration, example: {\\",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/info": {
            "get": {
                "description": "Get version and other server info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get server info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin.ServerInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/iptables/allow": {
            "post": {
                "description": "Add an ALLOW rule for a specific IP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Allow IP",
                "parameters": [
                    {
                        "description": "IP to allow",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iptables.ipRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/allow-all": {
            "post": {
                "description": "Remove the catch-all DROP rule",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Allow all traffic",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/block": {
            "post": {
                "description": "Add a DROP rule for a specific IP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Block IP",
                "parameters": [
                    {
                        "description": "IP to block",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iptables.ipRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/block-all": {
            "post": {
                "description": "Add a catch-all DROP rule at the end of the chain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Block all traffic",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/clean": {
            "post": {
                "description": "Remove the custom iptables chain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Clean iptables",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/flush": {
            "post": {
                "description": "Flush all rules in the custom chain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Flush iptables rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/init": {
            "post": {
                "description": "Initialize the custom iptables chain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Initialize iptables",
                "parameters": [
                    {
                        "description": "Initialization options",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/iptables.initRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/list": {
            "get": {
                "description": "List all rules in the custom chain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "List iptables rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/rules": {
            "get": {
                "description": "Get all configured proxy rules",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Get all rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Rule"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Set proxy rules (overrides existing rules)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Set rules",
                "parameters": [
                    {
                        "description": "List of rules to set",
                        "name": "rules",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Rule"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Rule"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove all proxy rules",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Flush all rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/ssl": {
            "get": {
                "description": "Check if dynamic SSL is currently enabled and configured on the proxy port",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ssl"
                ],
                "summary": "Get SSL status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.SSLInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Upload a PEM encoded certificate and private key to enable HTTPS on the proxy port",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ssl"
                ],
                "summary": "Set SSL certificate",
                "parameters": [
                    {
                        "description": "SSL Certificate and Key",
                        "name": "ssl",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SSLRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Clear the configured SSL certificate and disable HTTPS on the proxy port",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ssl"
                ],
                "summary": "Clear SSL certificate",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.ServerInfo": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "example": "0.0.1"
                }
            }
        },
        "iptables.initRequest": {
            "type": "object",
            "properties": {
                "chain_name": {
                    "type": "string",
                    "example": "KNOCK_FW"
                },
                "exempt_ports": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "9090",
                        "7999"
                    ]
                },
                "parent_chain": {
                    "description": "string or []string",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "INPUT",
                        "DOCKER-USER"
                    ]
                }
            }
        },
        "iptables.ipRequest": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string",
                    "example": "192.168.1.100"
                }
            }
        },
        "models.AuthConfig": {
            "type": "object",
            "properties": {
                "auth_cache_expire": {
                    "description": "Cache expiration in seconds (default 60)",
                    "type": "integer",
                    "example": 60
                },
                "auth_port": {
                    "description": "Local Auth Service Port",
                    "type": "integer",
                    "example": 3000
                },
                "auth_url": {
                    "description": "Relative Verify URL (default /auth)",
                    "type": "string",
                    "example": "/auth"
                },
                "login_url": {
                    "description": "Relative Login URL (default /login)",
                    "type": "string",
                    "example": "/login"
                }
            }
        },
        "models.Rule": {
            "type": "object",
            "properties": {
                "path": {
                    "description": "Path prefix to match (e.g., \"/api\")",
                    "type": "string",
                    "example": "/api"
                },
                "rewrite_html": {
                    "description": "If true, rewrites absolute paths in HTML response to include Path prefix.",
                    "type": "boolean",
                    "example": true
                },
                "strip_path": {
                    "description": "If true, strips the Path prefix from the request before forwarding.",
                    "type": "boolean",
                    "example": true
                },
                "target": {
                    "description": "Target URL (e.g., \"http://localhost:9091\")",
                    "type": "string",
                    "example": "http://localhost:8080"
                },
                "use_auth": {
                    "description": "If true, invokes global authentication check before proxying.",
                    "type": "boolean",
                    "example": false
                },
                "use_root_mode": {
                    "description": "If true, sets cookie and redirects matched path to /.",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "models.SSLInfo": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                }
            }
        },
        "models.SSLRequest": {
            "type": "object",
            "properties": {
                "cert": {
                    "type": "string",
                    "example": "-----BEGIN CERTIFICATE-----\n..."
                },
                "key": {
                    "type": "string",
                    "example": "-----BEGIN RSA PRIVATE KEY-----\n..."
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:9091",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go-Reauth-Proxy",
	Description:      "API for managing proxy rules and iptables.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
