// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/license/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth": {
            "get": {
                "description": "Get the configured global authentication URLs and port",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get global auth config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.AuthConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Set the global authentication configurations (port, auth_url, login_url)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set global auth config",
                "parameters": [
                    {
                        "description": "Auth configuration",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AuthConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/config/crawler-blocker": {
            "get": {
                "description": "Get the current crawler-blocker runtime configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get crawler blocker config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.CrawlerBlockerConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Replace the crawler-blocker runtime configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set crawler blocker config",
                "parameters": [
                    {
                        "description": "Crawler blocker config",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CrawlerBlockerConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.CrawlerBlockerConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/config/default-route": {
            "get": {
                "description": "Get the configured default route when root route is requested",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get default route",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Set the configured default route when root route is requested",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set default route",
                "parameters": [
                    {
                        "description": "Route configuration, example: {\\",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/config/forwarded-headers": {
            "get": {
                "description": "Get the current explicit forwarded-headers runtime configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get forwarded headers config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.ForwardedHeadersConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Replace the explicit forwarded-headers runtime configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set forwarded headers config",
                "parameters": [
                    {
                        "description": "Forwarded headers config",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ForwardedHeadersConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.ForwardedHeadersConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/config/preserve-host": {
            "get": {
                "description": "Get the current explicit preserve-host runtime configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get preserve host config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.PreserveHostConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Replace the explicit preserve-host runtime configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set preserve host config",
                "parameters": [
                    {
                        "description": "Preserve host config",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PreserveHostConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.PreserveHostConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/config/proxy-protocol": {
            "get": {
                "description": "Get whether the proxy port requires Proxy Protocol header",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get proxy protocol force",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin.proxyProtocolForceResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Enable or disable requiring Proxy Protocol header on proxy port",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set proxy protocol force",
                "parameters": [
                    {
                        "description": "Proxy protocol options",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.proxyProtocolForceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin.proxyProtocolForceResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/host-rules": {
            "get": {
                "description": "Get all exact-host reverse proxy rules",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "host-rules"
                ],
                "summary": "Get host rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.HostRule"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Replace all exact-host reverse proxy rules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "host-rules"
                ],
                "summary": "Set host rules",
                "parameters": [
                    {
                        "description": "List of host rules to set",
                        "name": "rules",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.HostRule"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.HostRule"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove all exact-host reverse proxy rules",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "host-rules"
                ],
                "summary": "Flush host rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/info": {
            "get": {
                "description": "Get version and other server info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get server info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin.ServerInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/iptables/allow": {
            "post": {
                "description": "Add an ALLOW rule for a specific IP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Allow IP",
                "parameters": [
                    {
                        "description": "IP to allow",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iptables.ipRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/allow-all": {
            "post": {
                "description": "Remove the catch-all DROP rule",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Allow all traffic",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/block": {
            "post": {
                "description": "Add a DROP rule for a specific IP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Block IP",
                "parameters": [
                    {
                        "description": "IP to block",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iptables.ipRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/block-all": {
            "post": {
                "description": "Add a catch-all DROP rule at the end of the chain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Block all traffic",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/clean": {
            "post": {
                "description": "Remove the custom iptables chain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Clean iptables",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/flush": {
            "post": {
                "description": "Flush all rules in the custom chain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Flush iptables rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/init": {
            "post": {
                "description": "Initialize the custom iptables chain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Initialize iptables",
                "parameters": [
                    {
                        "description": "Initialization options",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/iptables.initRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/list": {
            "get": {
                "description": "List all rules in the custom chain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "List iptables rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/remove": {
            "post": {
                "description": "Remove an ALLOW/BLOCK rule for a specific IP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Remove IP rule",
                "parameters": [
                    {
                        "description": "IP to remove",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iptables.ipRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/tcp-port/block": {
            "post": {
                "description": "Add a DROP rule for a specific source IP and TCP destination port",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Block TCP port for IP",
                "parameters": [
                    {
                        "description": "IP and TCP destination port to block",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iptables.tcpPortRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/tcp-port/remove": {
            "post": {
                "description": "Remove an ACCEPT/DROP rule for a specific source IP and TCP destination port",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Remove TCP port rule for IP",
                "parameters": [
                    {
                        "description": "IP and TCP destination port rule to remove",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iptables.tcpPortRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/iptables/tcp-redirect": {
            "post": {
                "description": "Ensure a tcp REDIRECT rule exists in nat PREROUTING for both iptables and ip6tables",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Ensure TCP redirect",
                "parameters": [
                    {
                        "description": "TCP redirect configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iptables.tcpRedirectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a tcp REDIRECT rule from nat PREROUTING for both iptables and ip6tables",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iptables"
                ],
                "summary": "Clear TCP redirect",
                "parameters": [
                    {
                        "description": "TCP redirect configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/iptables.tcpRedirectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/rules": {
            "get": {
                "description": "Get all configured proxy rules",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Get all rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Rule"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Set proxy rules (overrides existing rules)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Set rules",
                "parameters": [
                    {
                        "description": "List of rules to set",
                        "name": "rules",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Rule"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Rule"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove all proxy rules",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Flush all rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/ssl": {
            "get": {
                "description": "Check if dynamic SSL is currently enabled and configured on the proxy port",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ssl"
                ],
                "summary": "Get SSL status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.SSLInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Upload a legacy PEM certificate/key pair or a deployed SSL bundle to enable HTTPS on the proxy port",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ssl"
                ],
                "summary": "Set SSL certificate",
                "parameters": [
                    {
                        "description": "SSL deployment payload",
                        "name": "ssl",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SSLDeploymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Clear the configured SSL certificate and disable HTTPS on the proxy port",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ssl"
                ],
                "summary": "Clear SSL certificate",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/traffic": {
            "get": {
                "description": "Get proxy traffic stats (bytes in/out, active logged-in users in last 2 minutes, and 5xx count)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "traffic"
                ],
                "summary": "Get traffic stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/proxy.TrafficStats"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/traffic/active-ips": {
            "get": {
                "description": "Get recently active client IPs for one proxy host mapping",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "traffic"
                ],
                "summary": "Get active IPs for host traffic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Host mapping",
                        "name": "host",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/proxy.HostActiveIPsStats"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.ServerInfo": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "example": "0.0.1"
                }
            }
        },
        "admin.proxyProtocolForceRequest": {
            "type": "object",
            "properties": {
                "proxy_protocol_force": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "admin.proxyProtocolForceResponse": {
            "type": "object",
            "properties": {
                "proxy_protocol_force": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "iptables.initRequest": {
            "type": "object",
            "properties": {
                "chain_name": {
                    "type": "string",
                    "example": "KNOCK_FW"
                },
                "exempt_ports": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "7999",
                        "7999"
                    ]
                },
                "parent_chain": {
                    "description": "string or []string",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "INPUT",
                        "DOCKER-USER"
                    ]
                }
            }
        },
        "iptables.ipRequest": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string",
                    "example": "192.168.1.100"
                }
            }
        },
        "iptables.tcpPortRuleRequest": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string",
                    "example": "192.168.1.100"
                },
                "port": {
                    "type": "integer",
                    "example": 22
                }
            }
        },
        "iptables.tcpRedirectRequest": {
            "type": "object",
            "properties": {
                "listen_port": {
                    "type": "integer",
                    "example": 80
                },
                "target_port": {
                    "type": "integer",
                    "example": 7999
                }
            }
        },
        "models.AuthConfig": {
            "type": "object",
            "properties": {
                "aliyun_esa_enabled": {
                    "description": "Enables Alibaba Cloud ESA client IP/header handling.",
                    "type": "boolean",
                    "example": false
                },
                "auth_cache_ttl_seconds": {
                    "description": "Successful auth-result cache TTL in seconds. 0 disables the cache.",
                    "type": "integer",
                    "example": 1
                },
                "auth_cache_unauthorized_ttl_seconds": {
                    "description": "Unauthorized auth-result cache TTL in seconds. 0 disables the cache.",
                    "type": "integer",
                    "example": 1
                },
                "auth_host": {
                    "type": "string",
                    "example": "auth.example.com"
                },
                "auth_port": {
                    "description": "Local Auth Service Port",
                    "type": "integer",
                    "example": 3000
                },
                "auth_url": {
                    "description": "Relative Verify URL (default /api/auth/verify)",
                    "type": "string",
                    "example": "/api/auth/verify"
                },
                "edge_client_ip_enabled": {
                    "description": "Master switch for edge vendor client IP/header handling.",
                    "type": "boolean",
                    "example": false
                },
                "login_url": {
                    "description": "Relative Login URL (default /login)",
                    "type": "string",
                    "example": "/login"
                },
                "logout_url": {
                    "description": "Relative Logout URL (default /api/auth/logout)",
                    "type": "string",
                    "example": "/api/auth/logout"
                },
                "preflight_url": {
                    "description": "Relative Preflight URL (default /api/auth/preflight)",
                    "type": "string",
                    "example": "/api/auth/preflight"
                },
                "public_auth_base_url": {
                    "type": "string",
                    "example": "https://auth.example.com"
                },
                "public_http_port": {
                    "type": "integer",
                    "example": 80
                },
                "public_https_port": {
                    "type": "integer",
                    "example": 443
                },
                "tencent_edgeone_enabled": {
                    "description": "Enables Tencent EdgeOne client IP/header handling.",
                    "type": "boolean",
                    "example": false
                },
                "trust_forwarded_proto": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "models.BasicAuthConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "models.CrawlerBlockerConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.ForwardedHeadersConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "omit_targets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.HostLocation": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "example": "proxy"
                },
                "match": {
                    "type": "string",
                    "example": "prefix"
                },
                "path": {
                    "type": "string",
                    "example": "/api"
                },
                "response": {
                    "$ref": "#/definitions/models.HostLocationResponse"
                },
                "rewrite_html": {
                    "type": "boolean",
                    "example": true
                },
                "strip_path": {
                    "type": "boolean",
                    "example": true
                },
                "target": {
                    "type": "string",
                    "example": "wss://127.0.0.1:8080"
                }
            }
        },
        "models.HostLocationResponse": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "ok"
                },
                "content_type": {
                    "type": "string",
                    "example": "text/plain; charset=utf-8"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "models.HostRule": {
            "type": "object",
            "properties": {
                "access_mode": {
                    "type": "string",
                    "example": "login_first"
                },
                "basic_auth": {
                    "$ref": "#/definitions/models.BasicAuthConfig"
                },
                "favicon": {
                    "type": "string",
                    "example": "data:image/png;base64,..."
                },
                "host": {
                    "type": "string",
                    "example": "redis.example.com"
                },
                "locations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.HostLocation"
                    }
                },
                "preserve_host": {
                    "type": "boolean",
                    "example": true
                },
                "suppress_toolbar": {
                    "type": "boolean",
                    "example": false
                },
                "target": {
                    "type": "string",
                    "example": "http://127.0.0.1:5173"
                },
                "title": {
                    "type": "string",
                    "example": "Redis"
                },
                "use_auth": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.PreserveHostConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "omit_targets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Rule": {
            "type": "object",
            "properties": {
                "path": {
                    "description": "Path prefix to match (e.g., \"/api\")",
                    "type": "string",
                    "example": "/api"
                },
                "rewrite_html": {
                    "description": "If true, rewrites absolute paths in HTML response to include Path prefix.",
                    "type": "boolean",
                    "example": true
                },
                "strip_path": {
                    "description": "If true, strips the Path prefix from the request before forwarding.",
                    "type": "boolean",
                    "example": true
                },
                "target": {
                    "description": "Target URL (e.g., \"http://localhost:7996\" or \"ws://localhost:7996\")",
                    "type": "string",
                    "example": "ws://localhost:8080"
                },
                "use_auth": {
                    "description": "If true, invokes global authentication check before proxying.",
                    "type": "boolean",
                    "example": false
                },
                "use_root_mode": {
                    "description": "If true, sets cookie and redirects matched path to /.",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "models.SSLDeployedCertificate": {
            "type": "object",
            "properties": {
                "cert": {
                    "type": "string",
                    "example": "-----BEGIN CERTIFICATE-----\n..."
                },
                "id": {
                    "type": "string"
                },
                "is_default": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string",
                    "example": "-----BEGIN RSA PRIVATE KEY-----\n..."
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "models.SSLDeployedCertificateInfo": {
            "type": "object",
            "properties": {
                "domains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "is_default": {
                    "type": "boolean"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "models.SSLDeploymentMode": {
            "type": "string",
            "enum": [
                "single_active",
                "multi_sni"
            ],
            "x-enum-varnames": [
                "SSLDeploymentModeSingleActive",
                "SSLDeploymentModeMultiSNI"
            ]
        },
        "models.SSLDeploymentRequest": {
            "type": "object",
            "properties": {
                "cert": {
                    "type": "string",
                    "example": "-----BEGIN CERTIFICATE-----\n..."
                },
                "certificates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SSLDeployedCertificate"
                    }
                },
                "deployment_mode": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.SSLDeploymentMode"
                        }
                    ],
                    "example": "single_active"
                },
                "key": {
                    "type": "string",
                    "example": "-----BEGIN RSA PRIVATE KEY-----\n..."
                }
            }
        },
        "models.SSLInfo": {
            "type": "object",
            "properties": {
                "certificates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SSLDeployedCertificateInfo"
                    }
                },
                "deployment_mode": {
                    "$ref": "#/definitions/models.SSLDeploymentMode"
                },
                "enabled": {
                    "type": "boolean"
                }
            }
        },
        "proxy.HostActiveIPStats": {
            "type": "object",
            "properties": {
                "active_conns": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "last_seen_at": {
                    "type": "string"
                }
            }
        },
        "proxy.HostActiveIPsStats": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/proxy.HostActiveIPStats"
                    }
                },
                "window_seconds": {
                    "type": "integer"
                }
            }
        },
        "proxy.HostTrafficStats": {
            "type": "object",
            "properties": {
                "active_ip_count": {
                    "type": "integer"
                },
                "error_5xx": {
                    "type": "integer"
                },
                "host": {
                    "type": "string"
                },
                "total_in": {
                    "type": "integer"
                },
                "total_out": {
                    "type": "integer"
                }
            }
        },
        "proxy.TrafficStats": {
            "type": "object",
            "properties": {
                "active_conns": {
                    "type": "integer"
                },
                "by_host": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/proxy.HostTrafficStats"
                    }
                },
                "error_5xx": {
                    "type": "integer"
                },
                "total_in": {
                    "type": "integer"
                },
                "total_out": {
                    "type": "integer"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7996",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go-Reauth-Proxy",
	Description:      "API for managing proxy rules and iptables.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
